name: Hello World

on:
  push:
    branches: ['doug/workflow-testing']

jobs:
  Download dependencies:
    defaults:
      run:
        working_directory: ./expo
    steps:
      - run: ./scripts/download-dependencies.sh
  Set up android:
    defaults:
      run:
        working_directory: ./expo
    steps:
      - run: ./scripts/setup-react-android.sh  

